apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: smart-city-key-vault
  namespace: smart-city
spec:
  provider: azure
  secretObjects:
    - secretName: smart-city-secrets
      type: Opaque
      data:
        - objectName: database-url
          key: DATABASE_URL
        - objectName: rabbitmq-url
          key: RABBITMQ_URL
        - objectName: rabbitmq-user
          key: RABBITMQ_DEFAULT_USER
        - objectName: rabbitmq-password
          key: RABBITMQ_DEFAULT_PASS
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "KEY_VAULT_IDENTITY_CLIENT_ID"
    keyvaultName: "KEY_VAULT_NAME"
    tenantId: "AZURE_TENANT_ID"
    objects: |
      array:
        - |
          objectName: database-url
          objectType: secret
        - |
          objectName: rabbitmq-url
          objectType: secret
        - |
          objectName: rabbitmq-user
          objectType: secret
        - |
          objectName: rabbitmq-password
          objectType: secret
